id: I108D3EF0
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:21:52.278657+00:00
last_modified: 2022-12-14 18:21:52.278663+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-24T18:33:01.625Z'
  creationid: celso
  eft-text-id: UT22084-072-009
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_309-The_Sutra_on_Impermanence-v1
bases:
  B131:
    source_metadata: null
    order: 1
    base_file: B131.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
